import { StaffTicket } from './types'

export const mockTickets: StaffTicket[] = [
  {
    id: '1',
    ticketNumber: 'TKT-001',
    subject: 'Login issues on mobile app',
    userEmail: 'john@example.com',
    status: 'open',
    priority: 'high',
    platform: 'Mobile App',
    createdAt: '2024-04-20',
    updatedAt: '2024-04-20',
    description: 'User unable to log in on iOS app after latest update',
    assignedTo: 'Alice Johnson',
  },
  {
    id: '2',
    ticketNumber: 'TKT-002',
    subject: 'API documentation unclear',
    userEmail: 'dev@company.com',
    status: 'in-progress',
    priority: 'medium',
    platform: 'API Documentation',
    createdAt: '2024-04-18',
    updatedAt: '2024-04-21',
    description: 'Authentication section needs more examples',
    assignedTo: 'Bob Smith',
  },
  {
    id: '3',
    ticketNumber: 'TKT-003',
    subject: 'Payment integration error',
    userEmail: 'merchant@store.com',
    status: 'closed',
    priority: 'high',
    platform: 'Acme Corp Website',
    createdAt: '2024-04-15',
    updatedAt: '2024-04-19',
    description: 'Stripe integration throwing 500 errors',
    assignedTo: 'Carol White',
  },
  {
    id: '4',
    ticketNumber: 'TKT-004',
    subject: 'Feature request: Dark mode',
    userEmail: 'user@example.com',
    status: 'on-hold',
    priority: 'low',
    platform: 'Mobile App',
    createdAt: '2024-04-10',
    updatedAt: '2024-04-17',
    description: 'Users requesting dark mode toggle in settings',
    assignedTo: 'Bob Smith',
  },
  {
    id: '5',
    ticketNumber: 'TKT-005',
    subject: 'Database performance issues',
    userEmail: 'admin@company.com',
    status: 'in-progress',
    priority: 'high',
    platform: 'API Documentation',
    createdAt: '2024-04-22',
    updatedAt: '2024-04-23',
    description: 'Queries taking too long during peak hours',
    assignedTo: 'Alice Johnson',
  },
  {
    id: '6',
    ticketNumber: 'TKT-006',
    subject: 'Avatar upload fails silently',
    userEmail: 'grace@example.com',
    status: 'open',
    priority: 'medium',
    platform: 'Acme Corp Website',
    createdAt: '2024-04-24',
    updatedAt: '2024-04-24',
    description: 'Profile picture uploads stop at 90% with no visible error.',
    assignedTo: 'Farah Khan',
  },
]
