import { UserTicket } from './types'

export const mockUserTickets: UserTicket[] = [
  {
    id: '1',
    ticketNumber: 'TKT-056',
    subject: 'Unable to reset password',
    status: 'closed',
    createdAt: '2024-04-10',
    updatedAt: '2024-04-12',
    description: 'Password reset link not working',
    platform: 'Acme Corp Website',
  },
  {
    id: '2',
    ticketNumber: 'TKT-087',
    subject: 'Feature request: Export to CSV',
    status: 'in-progress',
    createdAt: '2024-04-15',
    updatedAt: '2024-04-20',
    description: 'Need ability to export data to CSV format',
    platform: 'Mobile App',
  },
  {
    id: '3',
    ticketNumber: 'TKT-092',
    subject: 'Dashboard loading slowly',
    status: 'open',
    createdAt: '2024-04-20',
    updatedAt: '2024-04-20',
    description: 'Dashboard takes 10+ seconds to load',
    platform: 'Acme Corp Website',
  },
  {
    id: '4',
    ticketNumber: 'TKT-101',
    subject: 'Billing receipt missing',
    status: 'on-hold',
    createdAt: '2024-04-21',
    updatedAt: '2024-04-22',
    description: 'I need the receipt for last month billing cycle.',
    platform: 'Acme Corp Website',
  },
  {
    id: '5',
    ticketNumber: 'TKT-108',
    subject: 'Push notifications delayed',
    status: 'open',
    createdAt: '2024-04-24',
    updatedAt: '2024-04-24',
    description: 'Notifications arrive 20 minutes late on Android devices.',
    platform: 'Mobile App',
  },
]
